spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/book_ssm_5_8?serverTimezone=UTC
    username: root
    password: 13241300
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml,classpath*:mybatis/*.xml,classpath*:sqlmap/**/*.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml,classpath*:mybatis/*.xml,classpath*:sqlmap/**/*.xml
