spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/book_ssm_5_8?serverTimezone=UTC
    username: root
    password: 13241300
logging:
  level:
    root: warn
    com.herion.dao: trace
  pattern:
    console: '%p%m%n'
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
